leftnav:
- identifier: 7ef7611e-267e-351d-d66a-08ac69c04c15
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: afbf8cb7-9497-eaef-f066-c82b003f9da5
  name: Readings
  url: /pages/readings
  weight: 20
- identifier: 583ecf97-3312-27a8-5879-623096460443
  name: Assignments
  url: /pages/assignments
  weight: 30
